name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Report rust version
      run: |
        rustc -vV
        rustup update
        rustc -vV

    - uses: actions/checkout@v5

    - name: Checkout the data repo
      uses: actions/checkout@v5
      with:
        repository: 'szabgab/pydigger-data'
        path: data


    - name: Check format
      run: cargo fmt --check
#    - name: Check clippy
#      run: cargo clippy -- --deny warnings
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Collect data
      run: cargo run -- --download --report

    - name: Tree
      run: tree data/

    - name: Commit new data
      run: |
        cd data
        GIT_STATUS=$(git status --porcelain)
        echo $GIT_STATUS
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        if [ "$GIT_STATUS" != "" ]; then git commit -m "Automated data collection"; fi
        if [ "$GIT_STATUS" != "" ]; then git push; fi
