name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Report rust version
      run: |
        rustc -vV
        rustup update
        rustc -vV

    - uses: actions/checkout@v5

    - name: Check format
      run: cargo fmt --check
#    - name: Check clippy
#      run: cargo clippy -- --deny warnings
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Linux binary
      uses: actions/upload-artifact@v5
      with:
        name: pydigger-linux-release
        path: target/release/pydigger

  other:
    runs-on: ubuntu-latest
    needs: build-linux

    steps:
    - name: Download binary
      uses: actions/download-artifact@v6
      with:
        name: pydigger-linux-release
        #github-token: ${{ secrets.GH_PAT }}
        path: pydigger
        #repository: szabgab/pydigger.rs

    - name: Get Help
      run: |
        ls -l
        tree pydigger
        #chmod +x pydigger
        #./pydigger -h


