name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Report rust version
      run: |
        rustc -vV
        rustup update
        rustc -vV

    - uses: actions/checkout@v5

    - name: Check format
      run: cargo fmt --check
#    - name: Check clippy
#      run: cargo clippy -- --deny warnings
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Collect data
      run: cargo run -- --download --report

    - name: Tree
      run: tree data/


